name: widd-example
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.9
    - matplotlib=3.6.2
    - pandas=1.5.1
    - pyparsing=3.0.9
    - requests=2.28.1
    - plotly=5.13.0
    - jupyter_contrib_nbextensions=0.7.0
